  name: Deploy to GCP

  on:
    pull_request:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            version: 'latest'
            project_id: spry-sentry-430715
            service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

        - name: Authenticate Docker with GCP Artifact Registry
          run: |
            echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

        - name: Build and push Docker image
          run: |
            docker build -t us-central1-docker.pkg.dev/spry-sentry-430715/streamlit-app/app:latest .
            docker push us-central1-docker.pkg.dev/spry-sentry-430715/streamlit-app/app:latest